### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by rtoal** [misaqpham/cmsi402#1]
Because every repo should have one

**Comment by bjohnson05** [comment]
Hi, Misa ---

Also, it shouldn't be called "cmsi402", especially when you are delivering
in two days.  Please update the project name.

thanks!

On Tue, May 3, 2016 at 4:13 PM, Ray Toal notifications@github.com wrote:

> Because every repo should have one
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/misaqpham/cmsi402/issues/1

## 

|B-)
